# H2 Database configuration for development
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
server.port=8089

# WhatsApp Configuration
whatsapp.token=EAAMTyMyMqdYBQ0xZC7NwXeHCknrQgf3FN43tBlo68QzpImDRZCMBDo1pji7XvpsZAsmSUqKXo5fyIFADsK5BzA9z6V7My7ZCaZAwuCxqAqu7pIHoyy09KN2Ue228laG0fMRuVgzZBZADVnDtx2D0HkXgsTtZA5YQH9aHDfIiWMZAzBxi5OPAB5JvFOV5TBcmiyoA4AMUvyMK6NXGunZAiQn8bFZCL9AaCVJjEVPnVuaXVCvHbzuN7ZBFDcwTXr5y4fpZAE7h8VqZA0vhaCfamlzHmLnQZCwlZAymRZCsIeEmhdhb7IQZDZD
whatsapp.phoneId=884949134712820
