server.port=8080

# Active profile
spring.profiles.active=dev

# WhatsApp API Configuration
# Set these as environment variables in Railway dashboard
whatsapp.token=EAAMTyMyMqdYBQ0uf0DMNRZAWhQMZBokxdES9afAAZB0g46KqijpDC5sl1CX1WJ7fYO6sqNrLqkj5bWCwI7skvELKyJeD6l2D9IgqSIcRaufkCPs8H3cZA7OMjPaeNeXdMIv5plAk3J2oJ2zQ2RmZA7JtOdC3W2kfGgCvZAXbzPY19DYdAAwg2dweuHeaFruCOFIO9B7kJwhKTZAToiujAkOeEj8fOauUfx8TUFeIN4vEizR8lozZAyp1ZBoTyZCPc70oyTTbErtQaMcC8q23kEhNWlvO5nhXrhnRaCHwhkEQZDZD
whatsapp.phoneId=884949134712820
